---
title: "Shiny Basics"
author: "Venture"
date: "2/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install the package
#install.packages("shiny")

# importing the packages
library(shiny)
library(shinyWidgets)

# Creating the UI
UI<-shinyUI(
  fluidPage(
    titlePanel(title = "This is my first shiny application"),
    sidebarLayout(
      sidebarPanel(h3("Enter personal information"),
        textInput("name","Enter your name",""),
        textInput("age","Enter your age",""),
        radioButtons("gender","Choose your gender","Male",choices = c("Male","Female")),
        sliderInput("height","Select your height",min = 0,max = 3,value = 2,step = 0.5),
        pickerInput("country","choose your country of residence",
                    selected ="Kenya",options = list(`actions-box`=T),
                    choices = c("Kenya","Uganda","Tanzania"),multiple = T),
        
        submitButton("Submit")
        
      ),
      mainPanel(h3("Display Personal Information"),
        textOutput("myname"),
        textOutput("myage"),
        textOutput("mygender"),
        textOutput("myheight"),
        textOutput("mycountry")
        
        
      )
    )
    
  )
)

server<-function(input,output,session){
  output$myname=renderText({paste("My name is:",input$name)})
  output$myage=renderText({paste("Your age is:",input$age,"Years")})
  output$mygender<-renderText({paste("Your gender is:",input$gender)})
  output$myheight<-renderText({paste("My height is:",input$height,"M")})
  output$mycountry<-renderText({paste("I am from this country:",input$country)})
  
}

shinyApp(UI,server)
 
```



```{r}
# Importing the packages
library(shiny)
library(shinyWidgets)
library(dplyr)

# creating the UI
ui<-shinyUI(fluidPage(
  titlePanel(title="using renderplot()"),
  sidebarLayout(
    sidebarPanel(),
    mainPanel()
  )
))


server<-function(input,output,session){
  
}

shinyApp(ui,server)

```
```{r}
library(ggplot2)
library(shiny)
library(dplyr)

# use selectinput() for the columns
UI<-shinyUI(fluidPage(
  titlePanel(title="Use selectinput for the columns"),
  sidebarLayout(
    sidebarPanel(
      selectInput("var","select the variable from the dataset",
                  choices = c("Sepal.Length"=1,"Petal.Width"=2,
                              "Sepal.Width"=3,"Petal.Length"=4),
                  selected = "Sepal.Length"),
      sliderInput("brek","Select the BINS of histogram",
                  min=20,max=60,value = 30),
      radioButtons("color","Select the color of your histogram",
                   choices=c("green","yellow","blue"),
                   selected = "green")
      
    ),
    mainPanel(
      tabsetPanel(type="tab",
                  tabPanel("Summary",verbatimTextOutput("sum")),
                  tabPanel("Structure",verbatimTextOutput("str")),
                  tabPanel("Data",tableOutput("data")),
                  tabPanel("Plot",plotOutput("myplot"))
                  
                  )
    )
  )
    
)
)

server<-function(input,output,session){
  colm<-reactive({as.numeric(input$var)})
  
  output$data<-renderTable({
    iris[colm()]
  })
  
  output$str<-renderPrint({
    str(iris)
  })
  
  output$sum<-renderPrint({
    summary(iris)
  })
  
  output$myplot <- renderPlot({
   
    hist(
      iris[, colm()],
      freq = FALSE,
      col = input$color,
      xlab = names(iris[colm()]),
      main = "Colored histogram",
      breaks = seq(0, max(iris[, colm()]), l = input$brek + 1)
    )
    
    # add a normal distribution line in histogram
    curve(dnorm(x,
                mean = mean(iris[, colm()]),
                sd = sd(iris[, colm()])),
          add = TRUE,
          col = "red",
          lwd=3) #line
  })
  
}


shinyApp(UI,server)
```